### ISSUE TITLE
Kapitan errors while compiling HELM charts

### ISSUE THREAD

**Issue by ademariag** [kapicorp/kapitan#358]
Kapitan errors while compiling HELM charts

1. Configure a helm chart
2. run `kapitan compile`

```kapitan compile -t poc01-istio

Helm binding is not available. Run 'make build_helm_binding' to create it
Compile error: failed to compile target: poc01-istio

```

**Expected behavior**
Chart gets generated

** Versions:**
```
$ kapitan--version
0.24.0

$ python --version
Python 2.7.16

$ pip3 --version
pip 19.1.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

I have used both the docker image `kapitan:ci` and user installed python kapitan

**Additional context**
see https://kubernetes.slack.com/archives/C981W2HD3/p1567418792016800

**Comment by ramaro** [comment]
@uberspot sounds like we missed the helm build.sh in CI?

**Comment by ademariag** [comment]
@ramaro this is confirmed also in the mainstream kapitan image `deepmind/kapitan`

**Comment by yoshi-1224** [comment]
@ademariag @uberspot @ramaro 
Confirmed the issue with the docker image `deepmind/kapitan`. This issue is raised by the following code:

```python
try:
    lib = ffi.dlopen(os.path.join(os.path.dirname(os.path.abspath(__file__)), "libtemplate.so"))
except (NameError, OSError):
    raise HelmBindingUnavailableError("Helm binding is not available. Run 'make build_helm_binding' to create it")
```

I just also ran `docker run -it --entrypoint /bin/bash deepmind/kapitan` to check if the `.so` file exists, and it does.

```
bash-5.0# ls /kapitan/kapitan/inputs/helm/ -l
total 10480
-rw-r--r--    1 root     root          4429 Aug 29 13:11 __init__.py
-rwxr-xr-x    1 root     root           409 Aug 29 13:11 build.sh
-rw-r--r--    1 root     root           406 Aug 29 13:11 cffi_build.py
-rw-r--r--    1 root     root           634 Aug 29 13:11 go.mod
-rw-------    1 root     root         10883 Aug 29 13:23 go.sum
-rw-r--r--    1 root     root           412 Aug 29 13:25 helm_binding.py
-rw-r--r--    1 root     root          1653 Aug 29 13:25 libtemplate.h
-rw-r--r--    1 root     root      10677944 Aug 29 13:25 libtemplate.so
-rw-r--r--    1 root     root          8732 Aug 29 13:11 template.go
```

So it might be something with the way file path is referred to inside docker image. Will keep you all posted.

**Comment by uberspot** [comment]
If the .so file is included in the images then i imagine the system just can't find it in the default library paths. We can try to either move the .so file there or define LD_LIBRARY_PATH to also include the path with the .so file. More info https://unix.stackexchange.com/questions/168340/where-is-ld-library-path-how-do-i-set-the-ld-library-path-env-variable

**Comment by yoshi-1224** [comment]
@uberspot @ademariag @ramaro 
Ok I looked at the actual exception thrown, and the issue is not whether the file exists but the following:

OSError: cannot load library '/kapitan/kapitan/inputs/helm/libtemplate.so': Error relocating /kapitan/kapitan/inputs/helm/libtemplate.so: : initial-exec TLS resolves to dynamic definition in /kapitan/kapitan/inputs/helm/libtemplate.so

Looking into how to resolve this.

**Comment by yoshi-1224** [comment]
@ademariag 
After some research I believe that Docker issue may not be so trivial to solve (because we are using alpine linux) and I need a bit more time to explore. Some pages I referred to:
- https://bugs.freedesktop.org/show_bug.cgi?id=35268
- https://stackoverflow.com/questions/55642942/python-on-alpine-ctypes-loadlibrary-failed-with-oserror-error-relocating-cc
- https://github.com/void-linux/void-packages/issues/3924

To compile the helm binding on pip installed kapitan, one can locate and execute `kapitan/inputs/helm/build.sh` (as you have pointed out on Slack).

@uberspot @ramaro 
Shall we make it a command for kapitan to build the helm binding? It might be inconvenient for the users who installed kapitan using pip (and therefore without `Makefile`) to locate and run `build.sh`?

**Comment by uberspot** [comment]
1) I agree on `Shall we make it a command for kapitan to build the helm binding? It might be inconvenient for the users who installed kapitan using pip (and therefore without Makefile) to locate and run build.sh?` It's definitely something that doesn't scale as a manual process. 

2) What if we switch our docker images to just debian as a way to have linking/compiling work properly?
The Alpine images are there for historic reasons. In my mind it makes sense to have all docker images we provide, based on the same OS, and just use the most stable one(?).

**Comment by yoshi-1224** [comment]
@uberspot 
> Also what if we switch our docker images to just debian as a way to have linking/compiling work properly?

I think this is a good idea. As far as I've looked into this, there is some issue with building c-shared objects on alpine (more specifically, using musl libc) using go. People tend to use something like `debian:<version>-slim` images which have the more common glibc as the alternative.

@ramaro What do you think?

**Comment by uberspot** [comment]
++ for the `-slim` version. Unless there's another requirement I'd recommend `xenial` which we also use in `.travis.yml`. That way we have the same everywhere and follow the same process to upgrade it all when the time comes.

**Comment by ramaro** [comment]
Totally agree on switching our docker images from alpine into slim debian!

But I'm not completely certain we need a command to build the helm binding. For pip users, I think it's preferable to build and package both macOS and linux bindings with kapitan and write import logic to decide what to load on runtime.

**Comment by yoshi-1224** [comment]
@ramaro

> For pip users, I think it's preferable to build and package both macOS and linux bindings with kapitan and write import logic to decide what to load on runtime.

If I understand correctly, does this mean we should ship the pre-built binaries such that `pip install kapitan` would automatically download them? And then by import logic you mean we confirm which platform kapitan is running on dynamically and then `dlopen` the appropriate binary for the platform?

**Comment by ramaro** [comment]
@yoshi-1224 Yep! :100:

**Comment by pbecotte** [comment]
I see that this ticket is closed, but so far as I can tell, the issue still exists in the Pypi package. I don't see a .so in the inputs/helm directory. Worse- I don't see any steps in your CI scripts or setup.py to actually generate the file. Finally- the build.sh script errors out with missing dependencies, and I know nothing about golang to take a shot at fixing that. Is this the intended behavior?

**Comment by ademariag** [comment]
are you on mac? or Linux

**Comment by caioaao** [comment]
Can confirm: versions 0.26.0, 0.27.0 and 0.27.2 also exits execution with:
```
Helm binding is not supported for Linux.
Or the binding does not exist.
```

**Comment by jmgilman** [comment]
Can confirm that the latest Pypi package available (0.27.4) is also resulting in the same error when attempting to compile with Helm charts. The Docker version works fine though, would it be worthwhile to open a new issue for the Pypi package specifically?

**Comment by ramaro** [comment]
Hey thanks for reporting. I think it's fine to just reopen this!

**Comment by UlyssesCB** [comment]
Any news here?
